version: '3.1'

services:
  mysql:
    image: mysql:8.3.0
    container_name: liferay-mysql-8.3.0
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p", "root" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./sql-scripts/:/docker-entrypoint-initdb.d/
      - liferay-mysql-8.3.0:/var/lib/mysql
    networks:
      - lportalnet

volumes:
  liferay-mysql-8.3.0:
    external: true

networks:
  lportalnet:
